[dr]
type = drive
scope = drive
token = {"access_token":"ya29.a0AZYkNZhw1TKR31eGJWc2hiYiacJby9kfzk7gk-g_SyqHLspIbZ0HY_rZSRtH9z4LxM7L1ZUXMCoabpZqSGRud3Zy_OO64tAnG1EwK75An9dDE8F4BEjdSpFBTNWfbgt4t7UOiVQeSXeGNcrw_0ZLn9TJSMBvUKgQlel0qVQgaCgYKAToSARISFQHGX2Miq5s7L17PY-HUApg1gf9V9A0175","token_type":"Bearer","refresh_token":"1//0gZfy6UbkqAw1CgYIARAAGBASNwF-L9IrmZRN4y2Jtfl3PVNzh8dYk6mKRoLTt3Nt6z6fYAkEsFinUrriotS1BicuydTsNVDJjNs","expiry":"2025-04-07T20:47:23.516657259+07:00"}